# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink: pretty
# relative_permalinks: true

# Setup
title: 제프의 Study Room
tagline: 제프의 블로그
description: 제프의 스터디룸에 오신것을 환영합니다. Welcome to Zef's Study Room!
url: https://ziponia.github.io
baseurl: ""
paginate: 10
paginate_path: "page:num"

github:
  repo: https://github.com/ziponia?tab=repositories

# About/contact
author:
  name: ziponia
  url: "https://github.com/ziponia"
  email: thtjwls@gmail.com

# Custom vars
version: 1.0.0
google_analytics: UA-140328041-1
disqus: ziponia
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
